### ISSUE TITLE
Can't translate, getting error.

### ISSUE THREAD

**Issue by Stanlyhalo** [matheuss/google-translate-api#102]
I'm getting this error:

{ Error
    at /rbd/pnpm-volume/d8614593-b135-49f8-804b-3686ad6243fd/node_modules/.registry.npmjs.org/google-translate-api/2.3.0/node_modules/google-translate-api/index.js:105:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) code: 'BAD_REQUEST' }

when doing this

    translate('Hello', {from: 'en', to: 'es'}).then(res => {
      console.log(res.text);
      console.log(res.from.text.autoCorrected);
      console.log(res.from.text.value);
      console.log(res.from.text.didYouMean);
    }).catch(err => {
      console.error(err);
    });

Why does this happen. I'm doing everything right.

**Comment by Himadri001** [comment]
Having the same problem, any update on this?

**Comment by mistersender** [comment]
I'm also seeing this error. looks like the underlying issue is a 403. wonder if google locked it down finally?

**Comment by ArtanisTheOne** [comment]
> I'm also seeing this error. looks like the underlying issue is a 403. wonder if google locked it down finally?

Incorrect token is being generated, check out my open[ issue](https://github.com/matheuss/google-translate-api/issues/113)
