### ISSUE TITLE
code: 'BAD_REQUEST

### ISSUE THREAD

**Issue by moyu5555** [matheuss/google-translate-api#106]
{ Error
    at /home/xiangying/server/core/node_modules/_google-translate-api@2.3.0@google-translate-api/index.js:105:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) code: 'BAD_REQUEST' }

**Comment by summerscar** [comment]
i have the same problem

**Comment by Hector6704** [comment]
same from me too, it doesn't translate anything at all

**Comment by kieuquangloc147** [comment]
@matheuss can you help us?

**Comment by wilsonwu** [comment]
This project is out of date, from the code, I found the page "https://translate.google.cn/translate_a/single" is 404.

**Comment by myusufid** [comment]
same, maybe have problem with API from google translate

**Comment by ezdiy** [comment]
Use https://github.com/davidwilsonfs/google-translate-token

**Comment by wilsonwu** [comment]
Use this: https://github.com/wilsonwu/translation-google
It support Chinese server.

**Comment by slaviboy** [comment]
Yea I have tried translating 200 sentences using a for loop, and after that a got that 'BAD_REQUEST'.
Google will send you the response with **statusMessage: 'Too Many Requests'**, so the problem is that you made too many request and you ID was blocked, and you are no longer able to request translation from the Google`s service :disappointed_relieved:

**Comment by doverradio** [comment]
> Use https://github.com/davidwilsonfs/google-translate-token

How do you use this?  

I also found this library, just tried to use for the last 10 minutes, then got errors of 'BAD_REQUEST'.  

How do you use the google-translate-token to solve?  Is that even still a solution?

**Comment by xsvetli1** [comment]
> Use this: https://github.com/wilsonwu/translation-google
> It support Chinese server.

This works! Thank you!

**Comment by tlamon** [comment]
> Use this: https://github.com/wilsonwu/translation-google It support Chinese server.

Thanks!
