### ISSUE TITLE
近期google-translate-api更新一次

### ISSUE THREAD

**Issue by sufeiweb** [matheuss/google-translate-api#110]
client：t=>webapp

返回值 body[0] 存在为空的情况，导致翻译会报错

需要修改为body[0]  =>  body[0] && body[0].forEach

由于主人断更了，可以移步 https://github.com/sufeiweb/google-translate-free 
稍后会发布到npm上，方便大家直接使用

**Comment by mashirozx** [comment]
谢谢！

不过有问题想请教一下。
我想在webpack里面调用这个模块，但是出现了下面的报错：
```
10:20:25 webpack.1 | WARNING in ./node_modules/got/source/request-as-event-emitter.js 157:21-28
10:20:25 webpack.1 | Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
10:20:25 webpack.1 |
10:20:25 webpack.1 | WARNING in ./node_modules/keyv/src/index.js 22:16-42
10:20:25 webpack.1 | Critical dependency: the request of a dependency is an expression
10:20:25 webpack.1 |
10:20:25 webpack.1 | ERROR in ./node_modules/@vitalets/google-translate-token/node_modules/got/index.js
10:20:25 webpack.1 | Module not found: Error: Can't resolve './package' in '/home/mastodon/live/node_modules/@vitalets/google-translate-token/node_modules/got'
10:20:25 webpack.1 |
10:20:25 webpack.1 | ERROR in ./node_modules/osenv/osenv.js
10:20:25 webpack.1 | Module not found: Error: Can't resolve 'child_process' in '/home/mastodon/live/node_modules/osenv'
10:20:25 webpack.1 |
10:20:25 webpack.1 | ERROR in ./node_modules/configstore/node_modules/mkdirp/index.js
10:20:25 webpack.1 | Module not found: Error: Can't resolve 'fs' in '/home/mastodon/live/node_modules/configstore/node_modules/mkdirp'
10:20:25 webpack.1 |
10:20:25 webpack.1 | ERROR in ./node_modules/got/source/utils/get-body-size.js
10:20:25 webpack.1 | Module not found: Error: Can't resolve 'fs' in '/home/mastodon/live/node_modules/got/source/utils'
10:20:25 webpack.1 |
10:20:25 webpack.1 | ERROR in ./node_modules/graceful-fs/graceful-fs.js
10:20:25 webpack.1 | Module not found: Error: Can't resolve 'fs' in '/home/mastodon/live/node_modules/graceful-fs'
10:20:25 webpack.1 |
10:20:25 webpack.1 | ERROR in ./node_modules/got/source/utils/timed-out.js
10:20:25 webpack.1 | Module not found: Error: Can't resolve 'net' in '/home/mastodon/live/node_modules/got/source/utils'
10:20:25 webpack.1 |
10:20:25 webpack.1 | ERROR in ./node_modules/defer-to-connect/dist/index.js
10:20:25 webpack.1 | Module not found: Error: Can't resolve 'tls' in '/home/mastodon/live/node_modules/defer-to-connect/dist'
10:20:25 webpack.1 | ℹ ｢wdm｣: Failed to compile.
```

难道是这个模块只能用在后端？

**Comment by mashirozx** [comment]
google translate 403了。。

{ HTTPError: Response code 403 (Forbidden)
Url: https://translate.google.com/translate_a/single?client=t&sl=auto&tl=ja&hl=ja&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=hello&tk=29979.29979
    at EventEmitter.emitter.on (/root/tmp/google-translate-server/node_modules/google-translate-free/node_modules/got/source/as-promise.js:74:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'HTTPError',
  host: 'translate.google.com',
  hostname: 'translate.google.com',
  method: 'GET',
  path:
   '/translate_a/single?client=t&sl=auto&tl=ja&hl=ja&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=hello&tk=29979.29979',
  socketPath: undefined,
  protocol: 'https:',
  url:
   'https://translate.google.com/translate_a/single?client=t&sl=auto&tl=ja&hl=ja&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=hello&tk=29979.29979',
  gotOptions:
   { path:
      '/translate_a/single?client=t&sl=auto&tl=ja&hl=ja&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=hello&tk=29979.29979',
     protocol: 'https:',
     slashes: true,
     auth: null,
     host: 'translate.google.com',
     port: null,
     hostname: 'translate.google.com',
     hash: null,
     search:
      '?client=t&sl=auto&tl=ja&hl=ja&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=hello&tk=29979.29979',
     pathname: '/translate_a/single',
     href:
      'https://translate.google.com/translate_a/single?client=t&sl=auto&tl=ja&hl=ja&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&kc=7&q=hello&tk=29979.29979',
     retry:
      { retries: [Function],
        methods: [Set],
        statusCodes: [Set],
        errorCodes: [Set] },
     headers:
      { 'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
        'accept-encoding': 'gzip, deflate' },
     hooks:
      { beforeRequest: [],
        beforeRedirect: [],
        beforeRetry: [],
        afterResponse: [],
        beforeError: [],
        init: [] },
     decompress: true,
     throwHttpErrors: true,
     followRedirect: true,
     stream: false,
     form: false,
     json: false,
     cache: false,
     useElectronNet: false,
     method: 'GET' },
  statusCode: 403,
  statusMessage: 'Forbidden',
  headers:
   { 'content-type': 'text/html; charset=utf-8',
     'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
     pragma: 'no-cache',
     expires: 'Mon, 01 Jan 1990 00:00:00 GMT',
     date: 'Thu, 10 Dec 2020 02:57:07 GMT',
     p3p:
      'CP="This is not a P3P policy! See g.co/p3phelp for more info."',
     'content-security-policy':
      'script-src \'report-sample\' \'nonce-2SS05MGfxTQswalInk95OQ\' \'unsafe-inline\';object-src \'none\';base-uri \'self\';report-uri /_/TranslateApiHttp/cspreport;worker-src \'self\'',
     'content-encoding': 'gzip',
     server: 'ESF',
     'x-xss-protection': '0',
     'x-content-type-options': 'nosniff',
     'set-cookie':
      [ 'NID=204=LaG63GHQSaYQ9KaHIEIqnc55OMtfBld5ib62t4cAaO3JmG-JUqdm-ODSw1fJM2f1rBsPLkmI7V9EQXFIvbwb7lxbyySbLGiVh9Eq4bTMDGjJyWrTqrwYu5DAJ__6dINd19ySc_aNYGbJnMX1W42DrzhoXJtRw7BP9Kwr32YFGTE; expires=Fri, 11-Jun-2021 02:57:07 GMT; path=/; domain=.google.com; HttpOnly' ],
     'alt-svc':
      'h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"',
     connection: 'close',
     'transfer-encoding': 'chunked' },
  body:
   '<html lang=en><meta charset=utf-8><meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width"><title>Error 403 (禁止)!!1</title><style nonce="2SS05MGfxTQswalInk95OQ">*{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{color:#222;text-align:unset;margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px;}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}pre{white-space:pre-wrap;}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}</style><div id="af-error-container"><a href=//www.google.com><span id=logo aria-label=Google></span></a><p><b>403.</b> <ins>エラーが発生しました。</ins><p>このページへのアクセス権限がありません。 <ins>その他の詳細は不明です。</ins></div>',
  code: 'BAD_REQUEST' }

**Comment by mashirozx** [comment]
加了UA也不行。。。

**Comment by dawangraoming** [comment]
same 403
