### ISSUE TITLE
BAD_REQUEST

### ISSUE THREAD

**Issue by JeshuwaBradley** [matheuss/google-translate-api#116]
Everytime i try translating i get this. What can be the problem?

Error
    at C:\Users\jeshu\desktop\bradley\shop\node_modules\google-translate-api\index.js:105:17
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'BAD_REQUEST'

**Comment by usmandilmeer** [comment]
i also get bad request

**Comment by CharnSrinivas** [comment]
Same here. : (

**Comment by Thomas-Boi** [comment]
Seems like Google might be block your IP. See the comments in [this thread](https://stackoverflow.com/a/40239218/11683637). I'm looking through all the sources and it seems that Google trying to get people to pay for the translation service. Strangely enough, they offer a free translation extension.

Out of curiosity, what solution did you guys use? I'm looking for one myself.
