### ISSUE TITLE
bad request

### ISSUE THREAD

**Issue by darkfunc** [matheuss/google-translate-api#128]
### When i try to translate text it occurs an error which i included below

`Error
    at /home/clerov/Builds/ai/backend/node_modules/.pnpm/google-translate-api@2.3.0/node_modules/google-translate-api/index.js:105:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'BAD_REQUEST'
}`

**Comment by ceving** [comment]
Same here:
~~~
Error
    at /home/szi/Nutrients/node_modules/google-translate-api/index.js:105:17
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'BAD_REQUEST'
}
~~~

**Comment by shellGrace** [comment]
I have the same problem now, have you solved it?
