### ISSUE TITLE
Different BAD_NETWORK issue?

### ISSUE THREAD

**Issue by skygragon** [matheuss/google-translate-api#50]
node: 8.1.4
npm: 5.3.0

```
{ Error: unable to get local issuer certificate
    at /Users/xxx/test/nodejs/node_modules/google-translate-token/index.js:103:25
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
  code: 'BAD_NETWORK',
  message: 'unable to get local issuer certificate' }
```

**Comment by extensionsapp** [comment]
Hey.
Google tightened the restrictions and now from a single IP address can make very few queries.
I added the use of a proxy server (IPv4, IPv6). Maybe my solution will help you.

https://github.com/extensionsapp/translatte

```javascript
const translatte = require('translatte');

// Translate string to English using proxy
translatte('Вы говорите на русском?', {
    from: 'ru',
    to: 'en',
    agents: [
        'Mozilla/5.0 (Windows NT 10.0; ...',
        'Mozilla/4.0 (Windows NT 10.0; ...',
        'Mozilla/5.0 (Windows NT 10.0; ...'
    ],
    proxies: [
        'LOGIN:PASSWORD@192.0.2.100:12345',
        'LOGIN:PASSWORD@192.0.2.200:54321'
    ]
}).then(res => {
    console.log(res);
}).catch(err => {
    console.error(err);
});
// { text: 'Do you speak Russian?', 
//   from: { 
//     language: { 
//       didYouMean: false, 
//       iso: 'ru' 
//     }, 
//     text: { 
//       autoCorrected: false, 
//       value: '', 
//       didYouMean: false 
//     } 
//   },
//   raw: '' }
```
