### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kibibyte7** [matheuss/google-translate-api#84]
i make a command translate for my discord bot but i have this error when the command run : 
(node:13004) UnhandledPromiseRejectionWarning: Error

**Comment by lloydaf** [comment]
Can you catch the error and try and log it?

**Comment by kibibyte7** [comment]
I still have the error even if I put a catch and log it

**Comment by kibibyte7** [comment]
(node:4020) UnhandledPromiseRejectionWarning: Error
    at c:\Users\JustMe\Desktop\7orNad0Bot-master\node_modules\google-translate-api\index.js:105:17
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:4020) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4020) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Foddy** [comment]
I get the exact same error :S

**Comment by thejeff77** [comment]
What version of npm and node are you using?

**Comment by Foddy** [comment]
I am facing this issue with NodeJS v11.1 and NPM v6.4.1

**Comment by kibibyte7** [comment]
node v10.11.0 npm v6.41

**Comment by dmitriyK1** [comment]
I'm getting such error:
```sh
node_modules/google-translate-api/index.js:105:17
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) code: 'BAD_REQUEST' }
```

**Comment by Cool-Programmer** [comment]
Hi everyone. If you're having bad request errors like me, use [https://github.com/k3rn31p4nic/google-translate-api](https://github.com/k3rn31p4nic/google-translate-api) module (identical to this one in terms of functionality).

**Comment by brolnickij** [comment]
Hello Friends! Go to the fork of this repository, which is now actively supported: https://github.com/vitalets/google-translate-api

**Comment by tyt34** [comment]
> Hello Friends! Go to the fork of this repository, which is now actively supported: https://github.com/vitalets/google-translate-api

ThankYou
